CREATE TABLE IF NOT EXISTS DEVICE(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    BRAND VARCHAR(100) NOT NULL,
    STATE ENUM('AVAILABLE','IN_USE','INACTIVE') NOT NULL,
    CREATION_TIME datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;